name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.1
      - run: dart pub get
      - run: dart analyze
      - run: dart test

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.1
      - run: dart pub get
      - run: dart analyze
      - run: dart test

  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  windows-tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.1
      - run: dart pub get
        working-directory: core
      - run: dart analyze
        working-directory: core
      - run: dart test
        working-directory: core
      - run: dart pub get
        working-directory: server
      - run: dart analyze
        working-directory: server
      - run: dart test
        working-directory: server

  windows-build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3
          channel: stable
      - run: choco install openssl -y --no-progress
        working-directory: .
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: kangoos-windows-x64
          path: app/build/windows/x64/runner/Release/
          if-no-files-found: error
